name: Continuous Delivery

on:
  pull_request:
    branches:
      - master

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fin-analysis"
          heroku_email: "igormcsouza@gmail.com"
          usedocker: true
